version: '3'
services:
  test_flight_hunter:
    image: test_flight_hunter
    build: .
    environment:
      - CHAT_ID=${CHAT_ID}
      - BOT_WATCHER_TOKEN=${BOT_WATCHER_TOKEN}
      - INTERVAL_CHECK=${INTERVAL_CHECK}
      - PORT=${PORT}
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: always
volumes:
  node_modules:
